public enum QuestionName
{
    //Initial
    INTRODUCTION,
    WHAT_TRAJECTORY,
    WHY_CURVED,
    HOW_MANY_AXES,
    //Quest 1
    NOTICE_ONLY_VERTICAL_MOTION,
    VERTICAL_IS_INDEPENDENT,
    VERTICAL_COMPONENT_FORMULA,
    TIME_OF_FLIGHT_CAN_BE_FOUND,
    WHICH_EQUATION_TIME_OF_FLIGHT,
    QUEST_1_COMPLETED,
    //Quest 2
    NOTICE_ONLY_HORIZONTAL_MOTION,
    ANY_HORIZONTAL_FORCE,
    IS_HORIZONTAL_VELOCITY_AFFECTED,
    HORIZONTAL_COMPONENT_FORMULA,
    RANGE_CAN_BE_FOUND,
    RANGE_FORMULA,
    QUEST_2_COMPLETED,
    //Explanations
    ONLY_VERTICAL_OBSERVABLE,
    ONLY_HORIZONTAL_OBSERVABLE,
    //Misc
    NOW_WE_MOVE_SIDEWAYS,
    NOW_WE_MOVE_UPWARDS
}
